# Generated by Django 3.0.7 on 2020-07-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=300)),
                ('address', models.TextField()),
            ],
        ),
    ]
